// Generated from Rocket League Tracker Network Skill Rating Distribution
#pragma once
#include <array>

namespace {

    struct RankThreshold {
        int minMmr;
        const char* tier;
        const char* division;
    };
    using TournamentRankThreshold = RankThreshold;

    static constexpr std::array<TournamentRankThreshold, 85> TournamentRankThresholds = {{{-4, "Bronze I", "Div I"},
                                                                                          {119, "Bronze I", "Div II"},
                                                                                          {138, "Bronze I", "Div III"},
                                                                                          {157, "Bronze I", "Div IV"},
                                                                                          {162, "Bronze II", "Div I"},
                                                                                          {179, "Bronze II", "Div II"},
                                                                                          {198, "Bronze II", "Div III"},
                                                                                          {217, "Bronze II", "Div IV"},
                                                                                          {221, "Bronze III", "Div I"},
                                                                                          {239, "Bronze III", "Div II"},
                                                                                          {258, "Bronze III", "Div III"},
                                                                                          {277, "Bronze III", "Div IV"},
                                                                                          {283, "Silver I", "Div I"},
                                                                                          {299, "Silver I", "Div II"},
                                                                                          {318, "Silver I", "Div III"},
                                                                                          {337, "Silver I", "Div IV"},
                                                                                          {342, "Silver II", "Div I"},
                                                                                          {359, "Silver II", "Div II"},
                                                                                          {378, "Silver II", "Div III"},
                                                                                          {397, "Silver II", "Div IV"},
                                                                                          {403, "Silver III", "Div I"},
                                                                                          {419, "Silver III", "Div II"},
                                                                                          {438, "Silver III", "Div III"},
                                                                                          {457, "Silver III", "Div IV"},
                                                                                          {461, "Gold I", "Div I"},
                                                                                          {478, "Gold I", "Div II"},
                                                                                          {498, "Gold I", "Div III"},
                                                                                          {517, "Gold I", "Div IV"},
                                                                                          {521, "Gold II", "Div I"},
                                                                                          {539, "Gold II", "Div II"},
                                                                                          {558, "Gold II", "Div III"},
                                                                                          {577, "Gold II", "Div IV"},
                                                                                          {581, "Gold III", "Div I"},
                                                                                          {598, "Gold III", "Div II"},
                                                                                          {618, "Gold III", "Div III"},
                                                                                          {637, "Gold III", "Div IV"},
                                                                                          {641, "Platinum I", "Div I"},
                                                                                          {659, "Platinum I", "Div II"},
                                                                                          {678, "Platinum I", "Div III"},
                                                                                          {697, "Platinum I", "Div IV"},
                                                                                          {701, "Platinum II", "Div I"},
                                                                                          {719, "Platinum II", "Div II"},
                                                                                          {738, "Platinum II", "Div III"},
                                                                                          {757, "Platinum II", "Div IV"},
                                                                                          {761, "Platinum III", "Div I"},
                                                                                          {779, "Platinum III", "Div II"},
                                                                                          {798, "Platinum III", "Div III"},
                                                                                          {817, "Platinum III", "Div IV"},
                                                                                          {824, "Diamond I", "Div I"},
                                                                                          {844, "Diamond I", "Div II"},
                                                                                          {868, "Diamond I", "Div III"},
                                                                                          {892, "Diamond I", "Div IV"},
                                                                                          {901, "Diamond II", "Div I"},
                                                                                          {924, "Diamond II", "Div II"},
                                                                                          {948, "Diamond II", "Div III"},
                                                                                          {972, "Diamond II", "Div IV"},
                                                                                          {981, "Diamond III", "Div I"},
                                                                                          {1004, "Diamond III", "Div II"},
                                                                                          {1028, "Diamond III", "Div III"},
                                                                                          {1052, "Diamond III", "Div IV"},
                                                                                          {1061, "Champion I", "Div I"},
                                                                                          {1096, "Champion I", "Div II"},
                                                                                          {1128, "Champion I", "Div III"},
                                                                                          {1162, "Champion I", "Div IV"},
                                                                                          {1181, "Champion II", "Div I"},
                                                                                          {1215, "Champion II", "Div II"},
                                                                                          {1254, "Champion II", "Div III"},
                                                                                          {1282, "Champion II", "Div IV"},
                                                                                          {1301, "Champion III", "Div I"},
                                                                                          {1337, "Champion III", "Div II"},
                                                                                          {1368, "Champion III", "Div III"},
                                                                                          {1402, "Champion III", "Div IV"},
                                                                                          {1421, "Grand Champion I", "Div I"},
                                                                                          {1460, "Grand Champion I", "Div II"},
                                                                                          {1498, "Grand Champion I", "Div III"},
                                                                                          {1537, "Grand Champion I", "Div IV"},
                                                                                          {1561, "Grand Champion II", "Div I"},
                                                                                          {1600, "Grand Champion II", "Div II"},
                                                                                          {1638, "Grand Champion II", "Div III"},
                                                                                          {1677, "Grand Champion II", "Div IV"},
                                                                                          {1701, "Grand Champion III", "Div I"},
                                                                                          {1745, "Grand Champion III", "Div II"},
                                                                                          {1788, "Grand Champion III", "Div III"},
                                                                                          {1832, "Grand Champion III", "Div IV"},
                                                                                          {1861, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> SoloDuelRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                              {114, "Bronze I", "Div II"},
                                                                              {128, "Bronze I", "Div III"},
                                                                              {143, "Bronze I", "Div IV"},
                                                                              {145, "Bronze II", "Div I"},
                                                                              {159, "Bronze II", "Div II"},
                                                                              {178, "Bronze II", "Div III"},
                                                                              {197, "Bronze II", "Div IV"},
                                                                              {215, "Bronze III", "Div I"},
                                                                              {219, "Bronze III", "Div II"},
                                                                              {238, "Bronze III", "Div III"},
                                                                              {257, "Bronze III", "Div IV"},
                                                                              {275, "Silver I", "Div I"},
                                                                              {279, "Silver I", "Div II"},
                                                                              {298, "Silver I", "Div III"},
                                                                              {317, "Silver I", "Div IV"},
                                                                              {335, "Silver II", "Div I"},
                                                                              {339, "Silver II", "Div II"},
                                                                              {358, "Silver II", "Div III"},
                                                                              {377, "Silver II", "Div IV"},
                                                                              {395, "Silver III", "Div I"},
                                                                              {399, "Silver III", "Div II"},
                                                                              {418, "Silver III", "Div III"},
                                                                              {437, "Silver III", "Div IV"},
                                                                              {455, "Gold I", "Div I"},
                                                                              {459, "Gold I", "Div II"},
                                                                              {478, "Gold I", "Div III"},
                                                                              {497, "Gold I", "Div IV"},
                                                                              {515, "Gold II", "Div I"},
                                                                              {519, "Gold II", "Div II"},
                                                                              {538, "Gold II", "Div III"},
                                                                              {557, "Gold II", "Div IV"},
                                                                              {575, "Gold III", "Div I"},
                                                                              {579, "Gold III", "Div II"},
                                                                              {598, "Gold III", "Div III"},
                                                                              {617, "Gold III", "Div IV"},
                                                                              {635, "Platinum I", "Div I"},
                                                                              {639, "Platinum I", "Div II"},
                                                                              {658, "Platinum I", "Div III"},
                                                                              {677, "Platinum I", "Div IV"},
                                                                              {695, "Platinum II", "Div I"},
                                                                              {699, "Platinum II", "Div II"},
                                                                              {718, "Platinum II", "Div III"},
                                                                              {737, "Platinum II", "Div IV"},
                                                                              {755, "Platinum III", "Div I"},
                                                                              {759, "Platinum III", "Div II"},
                                                                              {778, "Platinum III", "Div III"},
                                                                              {797, "Platinum III", "Div IV"},
                                                                              {815, "Diamond I", "Div I"},
                                                                              {819, "Diamond I", "Div II"},
                                                                              {838, "Diamond I", "Div III"},
                                                                              {857, "Diamond I", "Div IV"},
                                                                              {875, "Diamond II", "Div I"},
                                                                              {879, "Diamond II", "Div II"},
                                                                              {898, "Diamond II", "Div III"},
                                                                              {917, "Diamond II", "Div IV"},
                                                                              {934, "Diamond III", "Div I"},
                                                                              {939, "Diamond III", "Div II"},
                                                                              {958, "Diamond III", "Div III"},
                                                                              {977, "Diamond III", "Div IV"},
                                                                              {994, "Champion I", "Div I"},
                                                                              {999, "Champion I", "Div II"},
                                                                              {1018, "Champion I", "Div III"},
                                                                              {1037, "Champion I", "Div IV"},
                                                                              {1048, "Champion II", "Div I"},
                                                                              {1059, "Champion II", "Div II"},
                                                                              {1078, "Champion II", "Div III"},
                                                                              {1097, "Champion II", "Div IV"},
                                                                              {1107, "Champion III", "Div I"},
                                                                              {1119, "Champion III", "Div II"},
                                                                              {1138, "Champion III", "Div III"},
                                                                              {1157, "Champion III", "Div IV"},
                                                                              {1166, "Grand Champion I", "Div I"},
                                                                              {1180, "Grand Champion I", "Div II"},
                                                                              {1198, "Grand Champion I", "Div III"},
                                                                              {1217, "Grand Champion I", "Div IV"},
                                                                              {1226, "Grand Champion II", "Div I"},
                                                                              {1240, "Grand Champion II", "Div II"},
                                                                              {1258, "Grand Champion II", "Div III"},
                                                                              {1277, "Grand Champion II", "Div IV"},
                                                                              {1288, "Grand Champion III", "Div I"},
                                                                              {1300, "Grand Champion III", "Div II"},
                                                                              {1319, "Grand Champion III", "Div III"},
                                                                              {1336, "Grand Champion III", "Div IV"},
                                                                              {1341, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> DoublesRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                             {119, "Bronze I", "Div II"},
                                                                             {138, "Bronze I", "Div III"},
                                                                             {157, "Bronze I", "Div IV"},
                                                                             {169, "Bronze II", "Div I"},
                                                                             {179, "Bronze II", "Div II"},
                                                                             {198, "Bronze II", "Div III"},
                                                                             {217, "Bronze II", "Div IV"},
                                                                             {232, "Bronze III", "Div I"},
                                                                             {239, "Bronze III", "Div II"},
                                                                             {258, "Bronze III", "Div III"},
                                                                             {277, "Bronze III", "Div IV"},
                                                                             {291, "Silver I", "Div I"},
                                                                             {299, "Silver I", "Div II"},
                                                                             {318, "Silver I", "Div III"},
                                                                             {337, "Silver I", "Div IV"},
                                                                             {352, "Silver II", "Div I"},
                                                                             {359, "Silver II", "Div II"},
                                                                             {378, "Silver II", "Div III"},
                                                                             {397, "Silver II", "Div IV"},
                                                                             {411, "Silver III", "Div I"},
                                                                             {419, "Silver III", "Div II"},
                                                                             {438, "Silver III", "Div III"},
                                                                             {457, "Silver III", "Div IV"},
                                                                             {472, "Gold I", "Div I"},
                                                                             {479, "Gold I", "Div II"},
                                                                             {498, "Gold I", "Div III"},
                                                                             {517, "Gold I", "Div IV"},
                                                                             {533, "Gold II", "Div I"},
                                                                             {539, "Gold II", "Div II"},
                                                                             {558, "Gold II", "Div III"},
                                                                             {577, "Gold II", "Div IV"},
                                                                             {593, "Gold III", "Div I"},
                                                                             {599, "Gold III", "Div II"},
                                                                             {618, "Gold III", "Div III"},
                                                                             {637, "Gold III", "Div IV"},
                                                                             {653, "Platinum I", "Div I"},
                                                                             {659, "Platinum I", "Div II"},
                                                                             {678, "Platinum I", "Div III"},
                                                                             {697, "Platinum I", "Div IV"},
                                                                             {712, "Platinum II", "Div I"},
                                                                             {719, "Platinum II", "Div II"},
                                                                             {738, "Platinum II", "Div III"},
                                                                             {757, "Platinum II", "Div IV"},
                                                                             {772, "Platinum III", "Div I"},
                                                                             {779, "Platinum III", "Div II"},
                                                                             {798, "Platinum III", "Div III"},
                                                                             {817, "Platinum III", "Div IV"},
                                                                             {835, "Diamond I", "Div I"},
                                                                             {844, "Diamond I", "Div II"},
                                                                             {868, "Diamond I", "Div III"},
                                                                             {892, "Diamond I", "Div IV"},
                                                                             {914, "Diamond II", "Div I"},
                                                                             {924, "Diamond II", "Div II"},
                                                                             {948, "Diamond II", "Div III"},
                                                                             {972, "Diamond II", "Div IV"},
                                                                             {994, "Diamond III", "Div I"},
                                                                             {1004, "Diamond III", "Div II"},
                                                                             {1028, "Diamond III", "Div III"},
                                                                             {1052, "Diamond III", "Div IV"},
                                                                             {1075, "Champion I", "Div I"},
                                                                             {1095, "Champion I", "Div II"},
                                                                             {1128, "Champion I", "Div III"},
                                                                             {1162, "Champion I", "Div IV"},
                                                                             {1195, "Champion II", "Div I"},
                                                                             {1214, "Champion II", "Div II"},
                                                                             {1248, "Champion II", "Div III"},
                                                                             {1282, "Champion II", "Div IV"},
                                                                             {1314, "Champion III", "Div I"},
                                                                             {1335, "Champion III", "Div II"},
                                                                             {1368, "Champion III", "Div III"},
                                                                             {1402, "Champion III", "Div IV"},
                                                                             {1435, "Grand Champion I", "Div I"},
                                                                             {1462, "Grand Champion I", "Div II"},
                                                                             {1498, "Grand Champion I", "Div III"},
                                                                             {1537, "Grand Champion I", "Div IV"},
                                                                             {1575, "Grand Champion II", "Div I"},
                                                                             {1601, "Grand Champion II", "Div II"},
                                                                             {1638, "Grand Champion II", "Div III"},
                                                                             {1677, "Grand Champion II", "Div IV"},
                                                                             {1715, "Grand Champion III", "Div I"},
                                                                             {1744, "Grand Champion III", "Div II"},
                                                                             {1788, "Grand Champion III", "Div III"},
                                                                             {1832, "Grand Champion III", "Div IV"},
                                                                             {1860, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> StandardRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                              {119, "Bronze I", "Div II"},
                                                                              {138, "Bronze I", "Div III"},
                                                                              {157, "Bronze I", "Div IV"},
                                                                              {175, "Bronze II", "Div I"},
                                                                              {179, "Bronze II", "Div II"},
                                                                              {198, "Bronze II", "Div III"},
                                                                              {217, "Bronze II", "Div IV"},
                                                                              {235, "Bronze III", "Div I"},
                                                                              {239, "Bronze III", "Div II"},
                                                                              {258, "Bronze III", "Div III"},
                                                                              {277, "Bronze III", "Div IV"},
                                                                              {295, "Silver I", "Div I"},
                                                                              {299, "Silver I", "Div II"},
                                                                              {318, "Silver I", "Div III"},
                                                                              {337, "Silver I", "Div IV"},
                                                                              {355, "Silver II", "Div I"},
                                                                              {359, "Silver II", "Div II"},
                                                                              {378, "Silver II", "Div III"},
                                                                              {397, "Silver II", "Div IV"},
                                                                              {415, "Silver III", "Div I"},
                                                                              {419, "Silver III", "Div II"},
                                                                              {438, "Silver III", "Div III"},
                                                                              {457, "Silver III", "Div IV"},
                                                                              {475, "Gold I", "Div I"},
                                                                              {479, "Gold I", "Div II"},
                                                                              {498, "Gold I", "Div III"},
                                                                              {517, "Gold I", "Div IV"},
                                                                              {535, "Gold II", "Div I"},
                                                                              {539, "Gold II", "Div II"},
                                                                              {558, "Gold II", "Div III"},
                                                                              {577, "Gold II", "Div IV"},
                                                                              {595, "Gold III", "Div I"},
                                                                              {599, "Gold III", "Div II"},
                                                                              {618, "Gold III", "Div III"},
                                                                              {637, "Gold III", "Div IV"},
                                                                              {655, "Platinum I", "Div I"},
                                                                              {659, "Platinum I", "Div II"},
                                                                              {678, "Platinum I", "Div III"},
                                                                              {697, "Platinum I", "Div IV"},
                                                                              {715, "Platinum II", "Div I"},
                                                                              {719, "Platinum II", "Div II"},
                                                                              {738, "Platinum II", "Div III"},
                                                                              {757, "Platinum II", "Div IV"},
                                                                              {775, "Platinum III", "Div I"},
                                                                              {779, "Platinum III", "Div II"},
                                                                              {798, "Platinum III", "Div III"},
                                                                              {817, "Platinum III", "Div IV"},
                                                                              {835, "Diamond I", "Div I"},
                                                                              {844, "Diamond I", "Div II"},
                                                                              {868, "Diamond I", "Div III"},
                                                                              {892, "Diamond I", "Div IV"},
                                                                              {915, "Diamond II", "Div I"},
                                                                              {924, "Diamond II", "Div II"},
                                                                              {948, "Diamond II", "Div III"},
                                                                              {972, "Diamond II", "Div IV"},
                                                                              {995, "Diamond III", "Div I"},
                                                                              {1004, "Diamond III", "Div II"},
                                                                              {1028, "Diamond III", "Div III"},
                                                                              {1052, "Diamond III", "Div IV"},
                                                                              {1075, "Champion I", "Div I"},
                                                                              {1094, "Champion I", "Div II"},
                                                                              {1128, "Champion I", "Div III"},
                                                                              {1162, "Champion I", "Div IV"},
                                                                              {1195, "Champion II", "Div I"},
                                                                              {1214, "Champion II", "Div II"},
                                                                              {1248, "Champion II", "Div III"},
                                                                              {1282, "Champion II", "Div IV"},
                                                                              {1315, "Champion III", "Div I"},
                                                                              {1335, "Champion III", "Div II"},
                                                                              {1368, "Champion III", "Div III"},
                                                                              {1402, "Champion III", "Div IV"},
                                                                              {1435, "Grand Champion I", "Div I"},
                                                                              {1460, "Grand Champion I", "Div II"},
                                                                              {1500, "Grand Champion I", "Div III"},
                                                                              {1537, "Grand Champion I", "Div IV"},
                                                                              {1575, "Grand Champion II", "Div I"},
                                                                              {1600, "Grand Champion II", "Div II"},
                                                                              {1638, "Grand Champion II", "Div III"},
                                                                              {1677, "Grand Champion II", "Div IV"},
                                                                              {1712, "Grand Champion III", "Div I"},
                                                                              {1745, "Grand Champion III", "Div II"},
                                                                              {1788, "Grand Champion III", "Div III"},
                                                                              {1832, "Grand Champion III", "Div IV"},
                                                                              {1862, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> HoopsRankThresholds = {{{-116, "Bronze I", "Div I"},
                                                                           {132, "Bronze I", "Div II"},
                                                                           {168, "Bronze I", "Div III"},
                                                                           {189, "Bronze I", "Div IV"},
                                                                           {204, "Bronze II", "Div I"},
                                                                           {220, "Bronze II", "Div II"},
                                                                           {238, "Bronze II", "Div III"},
                                                                           {257, "Bronze II", "Div IV"},
                                                                           {276, "Bronze III", "Div I"},
                                                                           {279, "Bronze III", "Div II"},
                                                                           {298, "Bronze III", "Div III"},
                                                                           {317, "Bronze III", "Div IV"},
                                                                           {322, "Silver I", "Div I"},
                                                                           {335, "Silver I", "Div II"},
                                                                           {348, "Silver I", "Div III"},
                                                                           {365, "Silver I", "Div IV"},
                                                                           {375, "Silver II", "Div I"},
                                                                           {379, "Silver II", "Div II"},
                                                                           {398, "Silver II", "Div III"},
                                                                           {418, "Silver II", "Div IV"},
                                                                           {424, "Silver III", "Div I"},
                                                                           {435, "Silver III", "Div II"},
                                                                           {448, "Silver III", "Div III"},
                                                                           {462, "Silver III", "Div IV"},
                                                                           {475, "Gold I", "Div I"},
                                                                           {479, "Gold I", "Div II"},
                                                                           {498, "Gold I", "Div III"},
                                                                           {518, "Gold I", "Div IV"},
                                                                           {521, "Gold II", "Div I"},
                                                                           {535, "Gold II", "Div II"},
                                                                           {548, "Gold II", "Div III"},
                                                                           {562, "Gold II", "Div IV"},
                                                                           {575, "Gold III", "Div I"},
                                                                           {579, "Gold III", "Div II"},
                                                                           {598, "Gold III", "Div III"},
                                                                           {617, "Gold III", "Div IV"},
                                                                           {621, "Platinum I", "Div I"},
                                                                           {635, "Platinum I", "Div II"},
                                                                           {648, "Platinum I", "Div III"},
                                                                           {662, "Platinum I", "Div IV"},
                                                                           {675, "Platinum II", "Div I"},
                                                                           {679, "Platinum II", "Div II"},
                                                                           {698, "Platinum II", "Div III"},
                                                                           {717, "Platinum II", "Div IV"},
                                                                           {721, "Platinum III", "Div I"},
                                                                           {735, "Platinum III", "Div II"},
                                                                           {748, "Platinum III", "Div III"},
                                                                           {762, "Platinum III", "Div IV"},
                                                                           {775, "Diamond I", "Div I"},
                                                                           {779, "Diamond I", "Div II"},
                                                                           {798, "Diamond I", "Div III"},
                                                                           {817, "Diamond I", "Div IV"},
                                                                           {821, "Diamond II", "Div I"},
                                                                           {835, "Diamond II", "Div II"},
                                                                           {848, "Diamond II", "Div III"},
                                                                           {862, "Diamond II", "Div IV"},
                                                                           {875, "Diamond III", "Div I"},
                                                                           {879, "Diamond III", "Div II"},
                                                                           {898, "Diamond III", "Div III"},
                                                                           {917, "Diamond III", "Div IV"},
                                                                           {921, "Champion I", "Div I"},
                                                                           {935, "Champion I", "Div II"},
                                                                           {948, "Champion I", "Div III"},
                                                                           {962, "Champion I", "Div IV"},
                                                                           {975, "Champion II", "Div I"},
                                                                           {979, "Champion II", "Div II"},
                                                                           {998, "Champion II", "Div III"},
                                                                           {1017, "Champion II", "Div IV"},
                                                                           {1035, "Champion III", "Div I"},
                                                                           {1039, "Champion III", "Div II"},
                                                                           {1058, "Champion III", "Div III"},
                                                                           {1077, "Champion III", "Div IV"},
                                                                           {1095, "Grand Champion I", "Div I"},
                                                                           {1099, "Grand Champion I", "Div II"},
                                                                           {1118, "Grand Champion I", "Div III"},
                                                                           {1137, "Grand Champion I", "Div IV"},
                                                                           {1147, "Grand Champion II", "Div I"},
                                                                           {1160, "Grand Champion II", "Div II"},
                                                                           {1178, "Grand Champion II", "Div III"},
                                                                           {1197, "Grand Champion II", "Div IV"},
                                                                           {1204, "Grand Champion III", "Div I"},
                                                                           {1219, "Grand Champion III", "Div II"},
                                                                           {1238, "Grand Champion III", "Div III"},
                                                                           {1258, "Grand Champion III", "Div IV"},
                                                                           {1267, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> RumbleRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                            {108, "Bronze I", "Div II"},
                                                                            {129, "Bronze I", "Div III"},
                                                                            {142, "Bronze I", "Div IV"},
                                                                            {147, "Bronze II", "Div I"},
                                                                            {161, "Bronze II", "Div II"},
                                                                            {179, "Bronze II", "Div III"},
                                                                            {197, "Bronze II", "Div IV"},
                                                                            {207, "Bronze III", "Div I"},
                                                                            {221, "Bronze III", "Div II"},
                                                                            {238, "Bronze III", "Div III"},
                                                                            {257, "Bronze III", "Div IV"},
                                                                            {275, "Silver I", "Div I"},
                                                                            {279, "Silver I", "Div II"},
                                                                            {298, "Silver I", "Div III"},
                                                                            {317, "Silver I", "Div IV"},
                                                                            {335, "Silver II", "Div I"},
                                                                            {339, "Silver II", "Div II"},
                                                                            {358, "Silver II", "Div III"},
                                                                            {377, "Silver II", "Div IV"},
                                                                            {395, "Silver III", "Div I"},
                                                                            {399, "Silver III", "Div II"},
                                                                            {418, "Silver III", "Div III"},
                                                                            {437, "Silver III", "Div IV"},
                                                                            {455, "Gold I", "Div I"},
                                                                            {459, "Gold I", "Div II"},
                                                                            {478, "Gold I", "Div III"},
                                                                            {497, "Gold I", "Div IV"},
                                                                            {515, "Gold II", "Div I"},
                                                                            {519, "Gold II", "Div II"},
                                                                            {538, "Gold II", "Div III"},
                                                                            {557, "Gold II", "Div IV"},
                                                                            {575, "Gold III", "Div I"},
                                                                            {579, "Gold III", "Div II"},
                                                                            {598, "Gold III", "Div III"},
                                                                            {618, "Gold III", "Div IV"},
                                                                            {635, "Platinum I", "Div I"},
                                                                            {639, "Platinum I", "Div II"},
                                                                            {658, "Platinum I", "Div III"},
                                                                            {678, "Platinum I", "Div IV"},
                                                                            {695, "Platinum II", "Div I"},
                                                                            {699, "Platinum II", "Div II"},
                                                                            {718, "Platinum II", "Div III"},
                                                                            {737, "Platinum II", "Div IV"},
                                                                            {755, "Platinum III", "Div I"},
                                                                            {759, "Platinum III", "Div II"},
                                                                            {778, "Platinum III", "Div III"},
                                                                            {797, "Platinum III", "Div IV"},
                                                                            {815, "Diamond I", "Div I"},
                                                                            {819, "Diamond I", "Div II"},
                                                                            {838, "Diamond I", "Div III"},
                                                                            {857, "Diamond I", "Div IV"},
                                                                            {875, "Diamond II", "Div I"},
                                                                            {879, "Diamond II", "Div II"},
                                                                            {898, "Diamond II", "Div III"},
                                                                            {917, "Diamond II", "Div IV"},
                                                                            {935, "Diamond III", "Div I"},
                                                                            {939, "Diamond III", "Div II"},
                                                                            {958, "Diamond III", "Div III"},
                                                                            {977, "Diamond III", "Div IV"},
                                                                            {995, "Champion I", "Div I"},
                                                                            {999, "Champion I", "Div II"},
                                                                            {1018, "Champion I", "Div III"},
                                                                            {1037, "Champion I", "Div IV"},
                                                                            {1055, "Champion II", "Div I"},
                                                                            {1059, "Champion II", "Div II"},
                                                                            {1078, "Champion II", "Div III"},
                                                                            {1097, "Champion II", "Div IV"},
                                                                            {1115, "Champion III", "Div I"},
                                                                            {1124, "Champion III", "Div II"},
                                                                            {1148, "Champion III", "Div III"},
                                                                            {1172, "Champion III", "Div IV"},
                                                                            {1195, "Grand Champion I", "Div I"},
                                                                            {1204, "Grand Champion I", "Div II"},
                                                                            {1228, "Grand Champion I", "Div III"},
                                                                            {1252, "Grand Champion I", "Div IV"},
                                                                            {1274, "Grand Champion II", "Div I"},
                                                                            {1287, "Grand Champion II", "Div II"},
                                                                            {1308, "Grand Champion II", "Div III"},
                                                                            {1332, "Grand Champion II", "Div IV"},
                                                                            {1346, "Grand Champion III", "Div I"},
                                                                            {1371, "Grand Champion III", "Div II"},
                                                                            {1399, "Grand Champion III", "Div III"},
                                                                            {1427, "Grand Champion III", "Div IV"},
                                                                            {1446, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> DropshotRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                              {120, "Bronze I", "Div II"},
                                                                              {138, "Bronze I", "Div III"},
                                                                              {159, "Bronze I", "Div IV"},
                                                                              {175, "Bronze II", "Div I"},
                                                                              {180, "Bronze II", "Div II"},
                                                                              {198, "Bronze II", "Div III"},
                                                                              {219, "Bronze II", "Div IV"},
                                                                              {235, "Bronze III", "Div I"},
                                                                              {239, "Bronze III", "Div II"},
                                                                              {258, "Bronze III", "Div III"},
                                                                              {277, "Bronze III", "Div IV"},
                                                                              {295, "Silver I", "Div I"},
                                                                              {299, "Silver I", "Div II"},
                                                                              {318, "Silver I", "Div III"},
                                                                              {337, "Silver I", "Div IV"},
                                                                              {341, "Silver II", "Div I"},
                                                                              {355, "Silver II", "Div II"},
                                                                              {368, "Silver II", "Div III"},
                                                                              {382, "Silver II", "Div IV"},
                                                                              {395, "Silver III", "Div I"},
                                                                              {399, "Silver III", "Div II"},
                                                                              {418, "Silver III", "Div III"},
                                                                              {437, "Silver III", "Div IV"},
                                                                              {442, "Gold I", "Div I"},
                                                                              {455, "Gold I", "Div II"},
                                                                              {468, "Gold I", "Div III"},
                                                                              {482, "Gold I", "Div IV"},
                                                                              {495, "Gold II", "Div I"},
                                                                              {499, "Gold II", "Div II"},
                                                                              {518, "Gold II", "Div III"},
                                                                              {537, "Gold II", "Div IV"},
                                                                              {542, "Gold III", "Div I"},
                                                                              {555, "Gold III", "Div II"},
                                                                              {568, "Gold III", "Div III"},
                                                                              {582, "Gold III", "Div IV"},
                                                                              {595, "Platinum I", "Div I"},
                                                                              {599, "Platinum I", "Div II"},
                                                                              {618, "Platinum I", "Div III"},
                                                                              {637, "Platinum I", "Div IV"},
                                                                              {642, "Platinum II", "Div I"},
                                                                              {655, "Platinum II", "Div II"},
                                                                              {668, "Platinum II", "Div III"},
                                                                              {682, "Platinum II", "Div IV"},
                                                                              {695, "Platinum III", "Div I"},
                                                                              {699, "Platinum III", "Div II"},
                                                                              {718, "Platinum III", "Div III"},
                                                                              {737, "Platinum III", "Div IV"},
                                                                              {742, "Diamond I", "Div I"},
                                                                              {755, "Diamond I", "Div II"},
                                                                              {768, "Diamond I", "Div III"},
                                                                              {782, "Diamond I", "Div IV"},
                                                                              {795, "Diamond II", "Div I"},
                                                                              {799, "Diamond II", "Div II"},
                                                                              {818, "Diamond II", "Div III"},
                                                                              {837, "Diamond II", "Div IV"},
                                                                              {841, "Diamond III", "Div I"},
                                                                              {855, "Diamond III", "Div II"},
                                                                              {868, "Diamond III", "Div III"},
                                                                              {882, "Diamond III", "Div IV"},
                                                                              {895, "Champion I", "Div I"},
                                                                              {899, "Champion I", "Div II"},
                                                                              {918, "Champion I", "Div III"},
                                                                              {937, "Champion I", "Div IV"},
                                                                              {942, "Champion II", "Div I"},
                                                                              {955, "Champion II", "Div II"},
                                                                              {968, "Champion II", "Div III"},
                                                                              {982, "Champion II", "Div IV"},
                                                                              {995, "Champion III", "Div I"},
                                                                              {999, "Champion III", "Div II"},
                                                                              {1018, "Champion III", "Div III"},
                                                                              {1037, "Champion III", "Div IV"},
                                                                              {1055, "Grand Champion I", "Div I"},
                                                                              {1059, "Grand Champion I", "Div II"},
                                                                              {1078, "Grand Champion I", "Div III"},
                                                                              {1097, "Grand Champion I", "Div IV"},
                                                                              {1106, "Grand Champion II", "Div I"},
                                                                              {1120, "Grand Champion II", "Div II"},
                                                                              {1138, "Grand Champion II", "Div III"},
                                                                              {1157, "Grand Champion II", "Div IV"},
                                                                              {1168, "Grand Champion III", "Div I"},
                                                                              {1180, "Grand Champion III", "Div II"},
                                                                              {1198, "Grand Champion III", "Div III"},
                                                                              {1217, "Grand Champion III", "Div IV"},
                                                                              {1227, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> SnowdayRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                             {135, "Bronze I", "Div II"},
                                                                             {158, "Bronze I", "Div III"},
                                                                             {198, "Bronze I", "Div IV"},
                                                                             {211, "Bronze II", "Div I"},
                                                                             {224, "Bronze II", "Div II"},
                                                                             {243, "Bronze II", "Div III"},
                                                                             {260, "Bronze II", "Div IV"},
                                                                             {275, "Bronze III", "Div I"},
                                                                             {280, "Bronze III", "Div II"},
                                                                             {298, "Bronze III", "Div III"},
                                                                             {317, "Bronze III", "Div IV"},
                                                                             {321, "Silver I", "Div I"},
                                                                             {336, "Silver I", "Div II"},
                                                                             {348, "Silver I", "Div III"},
                                                                             {362, "Silver I", "Div IV"},
                                                                             {375, "Silver II", "Div I"},
                                                                             {379, "Silver II", "Div II"},
                                                                             {398, "Silver II", "Div III"},
                                                                             {418, "Silver II", "Div IV"},
                                                                             {421, "Silver III", "Div I"},
                                                                             {435, "Silver III", "Div II"},
                                                                             {448, "Silver III", "Div III"},
                                                                             {462, "Silver III", "Div IV"},
                                                                             {475, "Gold I", "Div I"},
                                                                             {479, "Gold I", "Div II"},
                                                                             {498, "Gold I", "Div III"},
                                                                             {517, "Gold I", "Div IV"},
                                                                             {521, "Gold II", "Div I"},
                                                                             {536, "Gold II", "Div II"},
                                                                             {548, "Gold II", "Div III"},
                                                                             {563, "Gold II", "Div IV"},
                                                                             {575, "Gold III", "Div I"},
                                                                             {579, "Gold III", "Div II"},
                                                                             {598, "Gold III", "Div III"},
                                                                             {618, "Gold III", "Div IV"},
                                                                             {621, "Platinum I", "Div I"},
                                                                             {635, "Platinum I", "Div II"},
                                                                             {648, "Platinum I", "Div III"},
                                                                             {662, "Platinum I", "Div IV"},
                                                                             {675, "Platinum II", "Div I"},
                                                                             {679, "Platinum II", "Div II"},
                                                                             {698, "Platinum II", "Div III"},
                                                                             {717, "Platinum II", "Div IV"},
                                                                             {721, "Platinum III", "Div I"},
                                                                             {735, "Platinum III", "Div II"},
                                                                             {748, "Platinum III", "Div III"},
                                                                             {763, "Platinum III", "Div IV"},
                                                                             {775, "Diamond I", "Div I"},
                                                                             {779, "Diamond I", "Div II"},
                                                                             {798, "Diamond I", "Div III"},
                                                                             {817, "Diamond I", "Div IV"},
                                                                             {822, "Diamond II", "Div I"},
                                                                             {835, "Diamond II", "Div II"},
                                                                             {848, "Diamond II", "Div III"},
                                                                             {862, "Diamond II", "Div IV"},
                                                                             {875, "Diamond III", "Div I"},
                                                                             {879, "Diamond III", "Div II"},
                                                                             {898, "Diamond III", "Div III"},
                                                                             {917, "Diamond III", "Div IV"},
                                                                             {921, "Champion I", "Div I"},
                                                                             {935, "Champion I", "Div II"},
                                                                             {948, "Champion I", "Div III"},
                                                                             {962, "Champion I", "Div IV"},
                                                                             {975, "Champion II", "Div I"},
                                                                             {979, "Champion II", "Div II"},
                                                                             {998, "Champion II", "Div III"},
                                                                             {1017, "Champion II", "Div IV"},
                                                                             {1035, "Champion III", "Div I"},
                                                                             {1039, "Champion III", "Div II"},
                                                                             {1058, "Champion III", "Div III"},
                                                                             {1077, "Champion III", "Div IV"},
                                                                             {1095, "Grand Champion I", "Div I"},
                                                                             {1099, "Grand Champion I", "Div II"},
                                                                             {1118, "Grand Champion I", "Div III"},
                                                                             {1137, "Grand Champion I", "Div IV"},
                                                                             {1147, "Grand Champion II", "Div I"},
                                                                             {1160, "Grand Champion II", "Div II"},
                                                                             {1178, "Grand Champion II", "Div III"},
                                                                             {1197, "Grand Champion II", "Div IV"},
                                                                             {1200, "Grand Champion III", "Div I"},
                                                                             {1219, "Grand Champion III", "Div II"},
                                                                             {1238, "Grand Champion III", "Div III"},
                                                                             {1257, "Grand Champion III", "Div IV"},
                                                                             {1263, "Supersonic Legend", ""}}};

    static constexpr std::array<RankThreshold, 85> HeatseekerRankThresholds = {{{-100, "Bronze I", "Div I"},
                                                                                {119, "Bronze I", "Div II"},
                                                                                {138, "Bronze I", "Div III"},
                                                                                {157, "Bronze I", "Div IV"},
                                                                                {175, "Bronze II", "Div I"},
                                                                                {179, "Bronze II", "Div II"},
                                                                                {198, "Bronze II", "Div III"},
                                                                                {217, "Bronze II", "Div IV"},
                                                                                {235, "Bronze III", "Div I"},
                                                                                {239, "Bronze III", "Div II"},
                                                                                {258, "Bronze III", "Div III"},
                                                                                {277, "Bronze III", "Div IV"},
                                                                                {295, "Silver I", "Div I"},
                                                                                {299, "Silver I", "Div II"},
                                                                                {318, "Silver I", "Div III"},
                                                                                {337, "Silver I", "Div IV"},
                                                                                {355, "Silver II", "Div I"},
                                                                                {359, "Silver II", "Div II"},
                                                                                {378, "Silver II", "Div III"},
                                                                                {397, "Silver II", "Div IV"},
                                                                                {401, "Silver III", "Div I"},
                                                                                {415, "Silver III", "Div II"},
                                                                                {428, "Silver III", "Div III"},
                                                                                {442, "Silver III", "Div IV"},
                                                                                {455, "Gold I", "Div I"},
                                                                                {459, "Gold I", "Div II"},
                                                                                {478, "Gold I", "Div III"},
                                                                                {497, "Gold I", "Div IV"},
                                                                                {515, "Gold II", "Div I"},
                                                                                {519, "Gold II", "Div II"},
                                                                                {538, "Gold II", "Div III"},
                                                                                {557, "Gold II", "Div IV"},
                                                                                {575, "Gold III", "Div I"},
                                                                                {579, "Gold III", "Div II"},
                                                                                {598, "Gold III", "Div III"},
                                                                                {617, "Gold III", "Div IV"},
                                                                                {621, "Platinum I", "Div I"},
                                                                                {635, "Platinum I", "Div II"},
                                                                                {648, "Platinum I", "Div III"},
                                                                                {662, "Platinum I", "Div IV"},
                                                                                {675, "Platinum II", "Div I"},
                                                                                {679, "Platinum II", "Div II"},
                                                                                {698, "Platinum II", "Div III"},
                                                                                {717, "Platinum II", "Div IV"},
                                                                                {735, "Platinum III", "Div I"},
                                                                                {739, "Platinum III", "Div II"},
                                                                                {758, "Platinum III", "Div III"},
                                                                                {777, "Platinum III", "Div IV"},
                                                                                {795, "Diamond I", "Div I"},
                                                                                {799, "Diamond I", "Div II"},
                                                                                {818, "Diamond I", "Div III"},
                                                                                {837, "Diamond I", "Div IV"},
                                                                                {855, "Diamond II", "Div I"},
                                                                                {859, "Diamond II", "Div II"},
                                                                                {878, "Diamond II", "Div III"},
                                                                                {897, "Diamond II", "Div IV"},
                                                                                {901, "Diamond III", "Div I"},
                                                                                {915, "Diamond III", "Div II"},
                                                                                {928, "Diamond III", "Div III"},
                                                                                {942, "Diamond III", "Div IV"},
                                                                                {955, "Champion I", "Div I"},
                                                                                {959, "Champion I", "Div II"},
                                                                                {978, "Champion I", "Div III"},
                                                                                {997, "Champion I", "Div IV"},
                                                                                {1012, "Champion II", "Div I"},
                                                                                {1019, "Champion II", "Div II"},
                                                                                {1038, "Champion II", "Div III"},
                                                                                {1057, "Champion II", "Div IV"},
                                                                                {1068, "Champion III", "Div I"},
                                                                                {1079, "Champion III", "Div II"},
                                                                                {1098, "Champion III", "Div III"},
                                                                                {1117, "Champion III", "Div IV"},
                                                                                {1133, "Grand Champion I", "Div I"},
                                                                                {1139, "Grand Champion I", "Div II"},
                                                                                {1160, "Grand Champion I", "Div III"},
                                                                                {1177, "Grand Champion I", "Div IV"},
                                                                                {1185, "Grand Champion II", "Div I"},
                                                                                {1199, "Grand Champion II", "Div II"},
                                                                                {1218, "Grand Champion II", "Div III"},
                                                                                {1237, "Grand Champion II", "Div IV"},
                                                                                {1246, "Grand Champion III", "Div I"},
                                                                                {1260, "Grand Champion III", "Div II"},
                                                                                {1278, "Grand Champion III", "Div III"},
                                                                                {1296, "Grand Champion III", "Div IV"},
                                                                                {1303, "Supersonic Legend", ""}}};

} // namespace
